version: 1

formatters:
  debugFormatter:
    format: '[%(asctime)s]%(levelname)s - %(filename)s#%(funcName)s:%(lineno)d: %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

  normalFormatter:
    format: '[%(asctime)s]%(levelname)s - %(name)s: %(message)s'
    datefmt: '%Y/%m/%d %H:%M:%S'

  accessFormatter:
    format: '%(message)s'

handlers:
  debugLogHandler:
    formatter: debugFormatter
    class: logging.handlers.TimedRotatingFileHandler
    level: DEBUG
    filename: log/debug.log
    encoding: utf8
    when: 'D'
    interval: 1
    backupCount: 14

  accessLogHandler:
    formatter: accessFormatter
    class: logging.handlers.TimedRotatingFileHandler
    level: INFO
    filename: log/access.log
    encoding: utf8
    when: 'D'
    interval: 1
    backupCount: 14

  consoleHandler:
    class: logging.StreamHandler
    level: WARNING
    formatter: normalFormatter
    stream: ext://sys.stdout

loggers:
  debug:
    handlers: [consoleHandler, debugLogHandler]
    level: DEBUG
    qualname: WSGI
    propagate: no

  waitress:
    handlers: [consoleHandler, debugLogHandler]
    level: DEBUG
    qualname: WAITRESS
    propagate: no

  wsgi:
    handlers: [accessLogHandler]
    level: INFO
    qualname: WSGI
    propagate: no

root:
  level: DEBUG
  handlers: [consoleHandler, debugLogHandler]